apiVersion: v1
kind: Pod
metadata:
  name: django
  labels:
    app: django
spec:
  containers:
  - name: djangocontainer
    image: djangoimage
    imagePullPolicy: Never
    command: ["python", "manage.py", "runserver"]